use 5.30.0;

my $Side = 240;
my $Color_Dark  = '#93877E';
my $Color_Light = '#FAF0E6';

my $Square_Side = $Side / 8;

open STDOUT, '>', 'src/lib/chessground-bg.svg';

printf "<!-- generated by gen-schessground-bg.pl -->\n";
printf "<svg width='$Side' height='$Side' xmlns='http://www.w3.org/2000/svg'>\n";

# dark squares
my $Stroke_Width = sqrt(2)/4 * $Square_Side*2/13;
printf "\t<g stroke='$Color_Dark' stroke-width='$Stroke_Width'>\n";
for ( my $d = 0; $d <= $Side*2; $d += $Square_Side*2/13 ) {
	printf "\t\t<line x1='%f' y1='%f' x2='%f' y2='%f' />\n", -5, $d+5, $d+5, -5;
}
printf "\t</g>\n";

# light squares
printf "\t<g fill='$Color_Light'>\n";
for ( my $rank = 0; $rank < 8; $rank++ ) {
	for ( my $file = $rank%2; $file < 8; $file += 2 ) {
		printf "\t\t<rect x='%d' y='%d' width='%d' height='%d' />\n", $file * $Square_Side, $rank * $Square_Side, $Square_Side, $Square_Side;
	}
}
printf "\t</g>\n";

printf "</svg>\n";
