use 5.30.0;
use warnings;

use MIME::Base64;

my $Color_White = '#FAF0E6';
my $Color_Black = '#282B28';
my $Color_Aura = '#FAF0E6'; # color of the background, for "aura" around pieces on dark squares
my $Aura_Width = 6; # actual width is 6-1.5 due to outline stroke width 1.5

open STDOUT, '>', 'src/lib/chessground-pieces.css';

printf "/* embedded SVGs for all chess pieces,\n";
printf " * generated by gen-schessground-pieces.pl.\n";
printf " * original shapes from chessground.cburnett.css\n";
printf " */\n";

my $pawn_fmt = '<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45"><path d="M22.5 9c-2.21 0-4 1.79-4 4 0 .89.29 1.71.78 2.38C17.33 16.5 16 18.59 16 21c0 2.03.94 3.84 2.41 5.03-3 1.06-7.41 5.55-7.41 13.47h23c0-7.92-4.41-12.41-7.41-13.47 1.47-1.19 2.41-3 2.41-5.03 0-2.41-1.33-4.5-3.28-5.62.49-.67.78-1.49.78-2.38 0-2.21-1.79-4-4-4z" fill="%s" stroke="%s" stroke-width="1.5" stroke-linecap="round"/></svg>';
$pawn_fmt = '<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45">
	<path d="M22.5 9c-2.21 0-4 1.79-4 4 0 .89.29 1.71.78 2.38C17.33 16.5 16 18.59 16 21c0 2.03.94 3.84 2.41 5.03-3 1.06-7.41 5.55-7.41 13.47h23c0-7.92-4.41-12.41-7.41-13.47 1.47-1.19 2.41-3 2.41-5.03 0-2.41-1.33-4.5-3.28-5.62.49-.67.78-1.49.78-2.38 0-2.21-1.79-4-4-4z" fill="none" stroke="%3$s" stroke-width="%4$f" stroke-linecap="round"/>
	<path d="M22.5 9c-2.21 0-4 1.79-4 4 0 .89.29 1.71.78 2.38C17.33 16.5 16 18.59 16 21c0 2.03.94 3.84 2.41 5.03-3 1.06-7.41 5.55-7.41 13.47h23c0-7.92-4.41-12.41-7.41-13.47 1.47-1.19 2.41-3 2.41-5.03 0-2.41-1.33-4.5-3.28-5.62.49-.67.78-1.49.78-2.38 0-2.21-1.79-4-4-4z" fill="%1$s" stroke="%2$s" stroke-width="1.5" stroke-linecap="round"/>
</svg>';
my $pawn_white = sprintf $pawn_fmt, $Color_White, $Color_Black, $Color_Aura, $Aura_Width;
my $pawn_black = sprintf $pawn_fmt, $Color_Black, $Color_Black, $Color_Aura, $Aura_Width;

my $rook_white = qq@<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45">
	<g fill="none" fill-rule="evenodd" stroke="$Color_Aura" stroke-width="$Aura_Width" stroke-linecap="round" stroke-linejoin="round">
		<path d="M9 39h27v-3H9v3zm3-3v-4h21v4H12zm-1-22V9h4v2h5V9h5v2h5V9h4v5" stroke-linecap="butt"/> <path d="M34 14l-3 3H14l-3-3"/> <path d="M31 17v12.5H14V17" stroke-linecap="butt" stroke-linejoin="miter"/> <path d="M31 29.5l1.5 2.5h-20l1.5-2.5"/> <path d="M11 14h23" fill="none" stroke-linejoin="miter"/>
	</g>
	<g fill="$Color_White" fill-rule="evenodd" stroke="$Color_Black" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
		<path d="M9 39h27v-3H9v3zm3-3v-4h21v4H12zm-1-22V9h4v2h5V9h5v2h5V9h4v5" stroke-linecap="butt"/> <path d="M34 14l-3 3H14l-3-3"/> <path d="M31 17v12.5H14V17" stroke-linecap="butt" stroke-linejoin="miter"/> <path d="M31 29.5l1.5 2.5h-20l1.5-2.5"/> <path d="M11 14h23" fill="none" stroke-linejoin="miter"/>
	</g>
</svg>@;
my $rook_black = qq@<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45">
	<g fill="none" fill-rule="evenodd" stroke="$Color_Aura" stroke-width="$Aura_Width" stroke-linecap="round" stroke-linejoin="round">
		<path d="M9 39h27v-3H9v3zm3.5-7l1.5-2.5h17l1.5 2.5h-20zm-.5 4v-4h21v4H12z" stroke-linecap="butt"/><path d="M14 29.5v-13h17v13H14z" stroke-linecap="butt" stroke-linejoin="miter"/><path d="M14 16.5L11 14h23l-3 2.5H14zM11 14V9h4v2h5V9h5v2h5V9h4v5H11z" stroke-linecap="butt"/><path d="M12 35.5h21m-20-4h19m-18-2h17m-17-13h17M11 14h23" fill="none" stroke="$Color_White" stroke-width="1" stroke-linejoin="miter"/>
	</g>
	<g fill="$Color_Black" fill-rule="evenodd" stroke="$Color_Black" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
		<path d="M9 39h27v-3H9v3zm3.5-7l1.5-2.5h17l1.5 2.5h-20zm-.5 4v-4h21v4H12z" stroke-linecap="butt"/><path d="M14 29.5v-13h17v13H14z" stroke-linecap="butt" stroke-linejoin="miter"/><path d="M14 16.5L11 14h23l-3 2.5H14zM11 14V9h4v2h5V9h5v2h5V9h4v5H11z" stroke-linecap="butt"/><path d="M12 35.5h21m-20-4h19m-18-2h17m-17-13h17M11 14h23" fill="none" stroke="$Color_White" stroke-width="1" stroke-linejoin="miter"/>
	</g>
</svg>@;

my $bishop_white = qq@<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45">
	<g fill="none" stroke="$Color_Aura" stroke-width="$Aura_Width" stroke-linecap="butt" stroke-linejoin="round">
		<path d="M9 36c3.39-.97 10.11.43 13.5-2 3.39 2.43 10.11 1.03 13.5 2 0 0 1.65.54 3 2-.68.97-1.65.99-3 .5-3.39-.97-10.11.46-13.5-1-3.39 1.46-10.11.03-13.5 1-1.354.49-2.323.47-3-.5 1.354-1.94 3-2 3-2z"/> <path d="M15 32c2.5 2.5 12.5 2.5 15 0 .5-1.5 0-2 0-2 0-2.5-2.5-4-2.5-4 5.5-1.5 6-11.5-5-15.5-11 4-10.5 14-5 15.5 0 0-2.5 1.5-2.5 4 0 0-.5.5 0 2z"/> <path d="M25 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 1 1 5 0z"/>
	</g>
	<g fill="none" fill-rule="evenodd" stroke="$Color_Black" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
		<g fill="$Color_White" stroke-linecap="butt">
			<path d="M9 36c3.39-.97 10.11.43 13.5-2 3.39 2.43 10.11 1.03 13.5 2 0 0 1.65.54 3 2-.68.97-1.65.99-3 .5-3.39-.97-10.11.46-13.5-1-3.39 1.46-10.11.03-13.5 1-1.354.49-2.323.47-3-.5 1.354-1.94 3-2 3-2z"/> <path d="M15 32c2.5 2.5 12.5 2.5 15 0 .5-1.5 0-2 0-2 0-2.5-2.5-4-2.5-4 5.5-1.5 6-11.5-5-15.5-11 4-10.5 14-5 15.5 0 0-2.5 1.5-2.5 4 0 0-.5.5 0 2z"/> <path d="M25 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 1 1 5 0z"/>
		</g>
		<path d="M17.5 26h10M15 30h15m-7.5-14.5v5M20 18h5" stroke-linejoin="miter"/>
	</g>
</svg>@;
my $bishop_black = qq@<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45">
	<g fill="none" stroke="$Color_Aura" stroke-width="$Aura_Width" stroke-linecap="butt" stroke-linejoin="round">
		<path d="M9 36c3.39-.97 10.11.43 13.5-2 3.39 2.43 10.11 1.03 13.5 2 0 0 1.65.54 3 2-.68.97-1.65.99-3 .5-3.39-.97-10.11.46-13.5-1-3.39 1.46-10.11.03-13.5 1-1.354.49-2.323.47-3-.5 1.354-1.94 3-2 3-2z"/><path d="M15 32c2.5 2.5 12.5 2.5 15 0 .5-1.5 0-2 0-2 0-2.5-2.5-4-2.5-4 5.5-1.5 6-11.5-5-15.5-11 4-10.5 14-5 15.5 0 0-2.5 1.5-2.5 4 0 0-.5.5 0 2z"/><path d="M25 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 1 1 5 0z"/>
	</g>
	<g fill="none" fill-rule="evenodd" stroke="$Color_Black" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
		<g fill="$Color_Black" stroke-linecap="butt">
			<path d="M9 36c3.39-.97 10.11.43 13.5-2 3.39 2.43 10.11 1.03 13.5 2 0 0 1.65.54 3 2-.68.97-1.65.99-3 .5-3.39-.97-10.11.46-13.5-1-3.39 1.46-10.11.03-13.5 1-1.354.49-2.323.47-3-.5 1.354-1.94 3-2 3-2z"/><path d="M15 32c2.5 2.5 12.5 2.5 15 0 .5-1.5 0-2 0-2 0-2.5-2.5-4-2.5-4 5.5-1.5 6-11.5-5-15.5-11 4-10.5 14-5 15.5 0 0-2.5 1.5-2.5 4 0 0-.5.5 0 2z"/><path d="M25 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 1 1 5 0z"/>
		</g>
		<path d="M17.5 26h10M15 30h15m-7.5-14.5v5M20 18h5" stroke="$Color_White" stroke-linejoin="miter"/>
	</g>
</svg>@;

my $knight_white = qq@<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45">
	<g fill="none" fill-rule="evenodd" stroke="$Color_Aura" stroke-width="$Aura_Width" stroke-linecap="round" stroke-linejoin="round">
		<path d="M22 10c10.5 1 16.5 8 16 29H15c0-9 10-6.5 8-21"/><path d="M24 18c.38 2.91-5.55 7.37-8 9-3 2-2.82 4.34-5 4-1.042-.94 1.41-3.04 0-3-1 0 .19 1.23-1 2-1 0-4.003 1-4-4 0-2 6-12 6-12s1.89-1.9 2-3.5c-.73-.994-.5-2-.5-3 1-1 3 2.5 3 2.5h2s.78-1.992 2.5-3c1 0 1 3 1 3"/>
	</g>
	<g fill="none" fill-rule="evenodd" stroke="$Color_Black" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
		<path d="M22 10c10.5 1 16.5 8 16 29H15c0-9 10-6.5 8-21" fill="$Color_White"/><path d="M24 18c.38 2.91-5.55 7.37-8 9-3 2-2.82 4.34-5 4-1.042-.94 1.41-3.04 0-3-1 0 .19 1.23-1 2-1 0-4.003 1-4-4 0-2 6-12 6-12s1.89-1.9 2-3.5c-.73-.994-.5-2-.5-3 1-1 3 2.5 3 2.5h2s.78-1.992 2.5-3c1 0 1 3 1 3" fill="$Color_White"/><path d="M9.5 25.5a.5.5 0 1 1-1 0 .5.5 0 1 1 1 0zm5.433-9.75a.5 1.5 30 1 1-.866-.5.5 1.5 30 1 1 .866.5z" fill="$Color_Black"/>
	</g>
</svg>@;
my $knight_black = qq@<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45">
	<g fill="none" fill-rule="evenodd" stroke="$Color_Aura" stroke-width="$Aura_Width" stroke-linecap="round" stroke-linejoin="round">
		<path d="M22 10c10.5 1 16.5 8 16 29H15c0-9 10-6.5 8-21"/>
		<path d="M24 18c.38 2.91-5.55 7.37-8 9-3 2-2.82 4.34-5 4-1.042-.94 1.41-3.04 0-3-1 0 .19 1.23-1 2-1 0-4.003 1-4-4 0-2 6-12 6-12s1.89-1.9 2-3.5c-.73-.994-.5-2-.5-3 1-1 3 2.5 3 2.5h2s.78-1.992 2.5-3c1 0 1 3 1 3"/>
	</g>
	<g fill="none" fill-rule="evenodd" stroke="$Color_Black" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
		<path d="M22 10c10.5 1 16.5 8 16 29H15c0-9 10-6.5 8-21" fill="$Color_Black"/><path d="M24 18c.38 2.91-5.55 7.37-8 9-3 2-2.82 4.34-5 4-1.042-.94 1.41-3.04 0-3-1 0 .19 1.23-1 2-1 0-4.003 1-4-4 0-2 6-12 6-12s1.89-1.9 2-3.5c-.73-.994-.5-2-.5-3 1-1 3 2.5 3 2.5h2s.78-1.992 2.5-3c1 0 1 3 1 3" fill="$Color_Black"/><path d="M9.5 25.5a.5.5 0 1 1-1 0 .5.5 0 1 1 1 0zm5.433-9.75a.5 1.5 30 1 1-.866-.5.5 1.5 30 1 1 .866.5z" fill="$Color_White" stroke="$Color_White"/><path d="M24.55 10.4l-.45 1.45.5.15c3.15 1 5.65 2.49 7.9 6.75S35.75 29.06 35.25 39l-.05.5h2.25l.05-.5c.5-10.06-.88-16.85-3.25-21.34-2.37-4.49-5.79-6.64-9.19-7.16l-.51-.1z" fill="$Color_White" stroke="none"/>
	</g>
</svg>@;

my $queen_white = qq@<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45">
	<g fill="none" fill-rule="evenodd" stroke="$Color_Aura" stroke-width="$Aura_Width" stroke-linecap="round" stroke-linejoin="round"><path d="M8 12a2 2 0 1 1-4 0 2 2 0 1 1 4 0zm16.5-4.5a2 2 0 1 1-4 0 2 2 0 1 1 4 0zM41 12a2 2 0 1 1-4 0 2 2 0 1 1 4 0zM16 8.5a2 2 0 1 1-4 0 2 2 0 1 1 4 0zM33 9a2 2 0 1 1-4 0 2 2 0 1 1 4 0z"/><path d="M9 26c8.5-1.5 21-1.5 27 0l2-12-7 11V11l-5.5 13.5-3-15-3 15-5.5-14V25L7 14l2 12z" stroke-linecap="butt"/><path d="M9 26c0 2 1.5 2 2.5 4 1 1.5 1 1 .5 3.5-1.5 1-1.5 2.5-1.5 2.5-1.5 1.5.5 2.5.5 2.5 6.5 1 16.5 1 23 0 0 0 1.5-1 0-2.5 0 0 .5-1.5-1-2.5-.5-2.5-.5-2 .5-3.5 1-2 2.5-2 2.5-4-8.5-1.5-18.5-1.5-27 0z" stroke-linecap="butt"/><path d="M11.5 30c3.5-1 18.5-1 22 0M12 33.5c6-1 15-1 21 0" fill="none"/></g>
	<g fill="$Color_White" fill-rule="evenodd" stroke="$Color_Black" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M8 12a2 2 0 1 1-4 0 2 2 0 1 1 4 0zm16.5-4.5a2 2 0 1 1-4 0 2 2 0 1 1 4 0zM41 12a2 2 0 1 1-4 0 2 2 0 1 1 4 0zM16 8.5a2 2 0 1 1-4 0 2 2 0 1 1 4 0zM33 9a2 2 0 1 1-4 0 2 2 0 1 1 4 0z"/><path d="M9 26c8.5-1.5 21-1.5 27 0l2-12-7 11V11l-5.5 13.5-3-15-3 15-5.5-14V25L7 14l2 12z" stroke-linecap="butt"/><path d="M9 26c0 2 1.5 2 2.5 4 1 1.5 1 1 .5 3.5-1.5 1-1.5 2.5-1.5 2.5-1.5 1.5.5 2.5.5 2.5 6.5 1 16.5 1 23 0 0 0 1.5-1 0-2.5 0 0 .5-1.5-1-2.5-.5-2.5-.5-2 .5-3.5 1-2 2.5-2 2.5-4-8.5-1.5-18.5-1.5-27 0z" stroke-linecap="butt"/><path d="M11.5 30c3.5-1 18.5-1 22 0M12 33.5c6-1 15-1 21 0" fill="none"/></g>
</svg>@;
my $queen_black = qq@<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45">
	<g fill="none" fill-rule="evenodd" stroke="$Color_Aura" stroke-width="$Aura_Width" stroke-linecap="round" stroke-linejoin="round">
		<g stroke-width="\@{[$Aura_Width-1.5]}"><circle cx="6" cy="12" r="2.75"/><circle cx="14" cy="9" r="2.75"/><circle cx="22.5" cy="8" r="2.75"/><circle cx="31" cy="9" r="2.75"/><circle cx="39" cy="12" r="2.75"/></g>
		<path d="M9 26c8.5-1.5 21-1.5 27 0l2.5-12.5L31 25l-.3-14.1-5.2 13.6-3-14.5-3 14.5-5.2-13.6L14 25 6.5 13.5 9 26z" stroke-linecap="butt"/>
		<path d="M9 26c0 2 1.5 2 2.5 4 1 1.5 1 1 .5 3.5-1.5 1-1.5 2.5-1.5 2.5-1.5 1.5.5 2.5.5 2.5 6.5 1 16.5 1 23 0 0 0 1.5-1 0-2.5 0 0 .5-1.5-1-2.5-.5-2.5-.5-2 .5-3.5 1-2 2.5-2 2.5-4-8.5-1.5-18.5-1.5-27 0z" stroke-linecap="butt"/>
		<path d="M11 38.5a35 35 1 0 0 23 0" fill="none" stroke-linecap="butt"/>
	</g>
	<g fill="$Color_Black" fill-rule="evenodd" stroke="$Color_Black" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
		<g stroke="none"><circle cx="6" cy="12" r="2.75"/><circle cx="14" cy="9" r="2.75"/><circle cx="22.5" cy="8" r="2.75"/><circle cx="31" cy="9" r="2.75"/><circle cx="39" cy="12" r="2.75"/></g>
		<path d="M9 26c8.5-1.5 21-1.5 27 0l2.5-12.5L31 25l-.3-14.1-5.2 13.6-3-14.5-3 14.5-5.2-13.6L14 25 6.5 13.5 9 26z" stroke-linecap="butt"/>
		<path d="M9 26c0 2 1.5 2 2.5 4 1 1.5 1 1 .5 3.5-1.5 1-1.5 2.5-1.5 2.5-1.5 1.5.5 2.5.5 2.5 6.5 1 16.5 1 23 0 0 0 1.5-1 0-2.5 0 0 .5-1.5-1-2.5-.5-2.5-.5-2 .5-3.5 1-2 2.5-2 2.5-4-8.5-1.5-18.5-1.5-27 0z" stroke-linecap="butt"/>
		<path d="M11 38.5a35 35 1 0 0 23 0" fill="none" stroke-linecap="butt"/>
		<path d="M11 29a35 35 1 0 1 23 0m-21.5 2.5h20m-21 3a35 35 1 0 0 22 0m-23 3a35 35 1 0 0 24 0" fill="none" stroke="$Color_White"/>
	</g>
</svg>@;

my $king_white = qq@<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45">
	<g fill="none" fill-rule="evenodd" stroke="$Color_Aura" stroke-width="$Aura_Width" stroke-linecap="round" stroke-linejoin="round">
		<path d="M22.5 11.63V6M20 8h5" stroke-linejoin="miter"/>
		<path d="M22.5 25s4.5-7.5 3-10.5c0 0-1-2.5-3-2.5s-3 2.5-3 2.5c-1.5 3 3 10.5 3 10.5" fill="$Color_White" stroke-linecap="butt" stroke-linejoin="miter"/>
		<path d="M11.5 37c5.5 3.5 15.5 3.5 21 0v-7s9-4.5 6-10.5c-4-6.5-13.5-3.5-16 4V27v-3.5c-3.5-7.5-13-10.5-16-4-3 6 5 10 5 10V37z" fill="$Color_White"/>
	</g>
	<g fill="none" fill-rule="evenodd" stroke="$Color_Black" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
		<path d="M22.5 11.63V6M20 8h5" stroke-linejoin="miter"/>
		<path d="M22.5 25s4.5-7.5 3-10.5c0 0-1-2.5-3-2.5s-3 2.5-3 2.5c-1.5 3 3 10.5 3 10.5" fill="$Color_White" stroke-linecap="butt" stroke-linejoin="miter"/>
		<path d="M11.5 37c5.5 3.5 15.5 3.5 21 0v-7s9-4.5 6-10.5c-4-6.5-13.5-3.5-16 4V27v-3.5c-3.5-7.5-13-10.5-16-4-3 6 5 10 5 10V37z" fill="$Color_White"/>
		<path d="M11.5 30c5.5-3 15.5-3 21 0m-21 3.5c5.5-3 15.5-3 21 0m-21 3.5c5.5-3 15.5-3 21 0"/>
	</g>
</svg>@;
my $king_black = qq@<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45">
	<g fill="none" fill-rule="evenodd" stroke="$Color_Aura" stroke-width="$Aura_Width" stroke-linecap="round" stroke-linejoin="round">
		<path d="M22.5 11.63V6" stroke-linejoin="miter"/>
		<path d="M22.5 25s4.5-7.5 3-10.5c0 0-1-2.5-3-2.5s-3 2.5-3 2.5c-1.5 3 3 10.5 3 10.5" fill="$Color_Black" stroke-linecap="butt" stroke-linejoin="miter"/>
		<path d="M11.5 37c5.5 3.5 15.5 3.5 21 0v-7s9-4.5 6-10.5c-4-6.5-13.5-3.5-16 4V27v-3.5c-3.5-7.5-13-10.5-16-4-3 6 5 10 5 10V37z" fill="$Color_Black"/>
		<path d="M20 8h5" stroke-linejoin="miter"/>
	</g>
	<g fill="none" fill-rule="evenodd" stroke="$Color_Black" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
		<path d="M22.5 11.63V6" stroke-linejoin="miter"/>
		<path d="M22.5 25s4.5-7.5 3-10.5c0 0-1-2.5-3-2.5s-3 2.5-3 2.5c-1.5 3 3 10.5 3 10.5" fill="$Color_Black" stroke-linecap="butt" stroke-linejoin="miter"/>
		<path d="M11.5 37c5.5 3.5 15.5 3.5 21 0v-7s9-4.5 6-10.5c-4-6.5-13.5-3.5-16 4V27v-3.5c-3.5-7.5-13-10.5-16-4-3 6 5 10 5 10V37z" fill="$Color_Black"/>
		<path d="M20 8h5" stroke-linejoin="miter"/>
		<path d="M32 29.5s8.5-4 6.03-9.65C34.15 14 25 18 22.5 24.5l.01 2.1-.01-2.1C20 18 9.906 14 6.997 19.85c-2.497 5.65 4.853 9 4.853 9" stroke="$Color_White"/>
		<path d="M11.5 30c5.5-3 15.5-3 21 0m-21 3.5c5.5-3 15.5-3 21 0m-21 3.5c5.5-3 15.5-3 21 0" stroke="$Color_White"/>
	</g>
</svg>@;

printf ".cg-wrap piece.pawn.white { background-image: url('data:image/svg+xml;base64,%s'); }\n", encode_base64($pawn_white,'');
printf ".cg-wrap piece.pawn.black { background-image: url('data:image/svg+xml;base64,%s'); }\n", encode_base64($pawn_black,'');
printf ".cg-wrap piece.rook.white { background-image: url('data:image/svg+xml;base64,%s'); }\n", encode_base64($rook_white,'');
printf ".cg-wrap piece.rook.black { background-image: url('data:image/svg+xml;base64,%s'); }\n", encode_base64($rook_black,'');
printf ".cg-wrap piece.bishop.white { background-image: url('data:image/svg+xml;base64,%s'); }\n", encode_base64($bishop_white,'');
printf ".cg-wrap piece.bishop.black { background-image: url('data:image/svg+xml;base64,%s'); }\n", encode_base64($bishop_black,'');
printf ".cg-wrap piece.knight.white { background-image: url('data:image/svg+xml;base64,%s'); }\n", encode_base64($knight_white,'');
printf ".cg-wrap piece.knight.black { background-image: url('data:image/svg+xml;base64,%s'); }\n", encode_base64($knight_black,'');
printf ".cg-wrap piece.queen.white { background-image: url('data:image/svg+xml;base64,%s'); }\n", encode_base64($queen_white,'');
printf ".cg-wrap piece.queen.black { background-image: url('data:image/svg+xml;base64,%s'); }\n", encode_base64($queen_black,'');
printf ".cg-wrap piece.king.white { background-image: url('data:image/svg+xml;base64,%s'); }\n", encode_base64($king_white,'');
printf ".cg-wrap piece.king.black { background-image: url('data:image/svg+xml;base64,%s'); }\n", encode_base64($king_black,'');
